import type { Metadata } from "next";

// ——— Styles ———
import "./globals.css";

// ——— Components ———
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

// ——— Metadata ———
export const metadata: Metadata = {
  title: "Cook And Share",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
